# Generated by Django 3.0.2 on 2020-01-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_First_Name', models.CharField(max_length=100)),
                ('Employee_Last_Name', models.CharField(max_length=100)),
                ('Company_Division', models.CharField(max_length=100)),
                ('Sanergy_Department', models.CharField(max_length=100)),
                ('Sanergy_Department_Unit', models.CharField(max_length=100)),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Work_Email', models.CharField(max_length=100)),
            ],
        ),
    ]
