# Generated by Django 3.0.2 on 2020-02-12 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Employee_First_Name', models.CharField(max_length=100)),
                ('Employee_Last_Name', models.CharField(max_length=100, null=True)),
                ('Employee_Full_Name', models.CharField(max_length=50)),
                ('Company_Division', models.CharField(blank=True, max_length=100)),
                ('Sanergy_Department', models.CharField(blank=True, max_length=100)),
                ('Sanergy_Department_Unit', models.CharField(max_length=100, null=True)),
                ('Employee_Active', models.BooleanField(default=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('HR_Employee_ID', models.EmailField(max_length=254, null=True, unique=True)),
                ('Line_Manager', models.CharField(max_length=100, null=True)),
                ('IsDeleted', models.BooleanField(null=True)),
                ('Image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Date_Of_Birth', models.DateField(default=django.utils.timezone.now)),
                ('Joined_Date', models.DateField(default=django.utils.timezone.now)),
                ('Phone_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_employee', models.BooleanField(default=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
