# Generated by Django 3.0.2 on 2020-03-02 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Employee_First_Name', models.CharField(max_length=100, null=True)),
                ('Employee_Last_Name', models.CharField(max_length=100, null=True)),
                ('Employee_Full_Name', models.CharField(max_length=100)),
                ('Company_Division', models.CharField(blank=True, max_length=100)),
                ('Employee_Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Sanergy_Department', models.CharField(max_length=100, null=True)),
                ('Sanergy_Department_Unit', models.CharField(max_length=100, null=True)),
                ('Talent_Partner', models.CharField(blank=True, max_length=100, null=True)),
                ('Team_Lead', models.CharField(blank=True, max_length=100, null=True)),
                ('Employee_Active', models.BooleanField(default=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('HR_Employee_ID', models.EmailField(max_length=254, null=True, unique=True)),
                ('Line_Manager', models.CharField(max_length=100, null=True)),
                ('IsDeleted', models.BooleanField(null=True)),
                ('Image', models.FileField(default='default.jpg', upload_to='profile_pics')),
                ('Date_Of_Birth', models.DateField(default=django.utils.timezone.now)),
                ('Joined_Date', models.DateField(default=django.utils.timezone.now)),
                ('Phone_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_employee', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
