# Generated by Django 3.0.2 on 2020-04-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('Employee_First_Name',)},
        ),
    ]
