# Generated by Django 3.0.2 on 2020-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200212_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Sanergy_Department',
            new_name='Employee_Department',
        ),
        migrations.AddField(
            model_name='employee',
            name='Talent_Partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Team_Lead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
