# Generated by Django 3.0.2 on 2020-02-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200213_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Sanergy_Department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
