# Generated by Django 3.0.2 on 2020-04-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_auto_20200325_0603'),
        ('employee', '0003_employee_employee_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Sanergy_Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.SanergyDepartment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Sanergy_Department_Unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.SanergyDepartmentUnit'),
        ),
    ]
