# Generated by Django 3.0.2 on 2020-02-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_sanergy_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_Department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
