# Generated by Django 3.0.2 on 2020-02-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200214_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_First_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
