# Generated by Django 3.0.2 on 2020-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Sanergy_Department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Sanergy_Department_Unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
