# Generated by Django 3.0.2 on 2020-04-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200402_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_Middle_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
