# Generated by Django 3.0.2 on 2020-04-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_employeeleaverequest_employee'),
        ('employee', '0003_auto_20200415_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Sanergy_Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.SanergyDepartment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Sanergy_Department_Unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.SanergyDepartmentUnit'),
        ),
    ]
