# Generated by Django 3.0.2 on 2020-04-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200415_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Sanergy_Department_Unit',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Sanergy_Department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
