# Generated by Django 3.0.2 on 2020-04-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Sanergy_Department_Unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
