# Generated by Django 3.0.2 on 2020-04-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200413_1655'),
        ('leave_management', '0004_auto_20200413_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='coverage_plans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='line_manager_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_manager_account', to='employee.Employee'),
        ),
    ]
