# Generated by Django 3.0.2 on 2020-01-28 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leave_Types', models.CharField(choices=[('SICK_LEAVE', 'SICK_LEAVE'), ('STUDY_LEAVE', 'STUDY_LEAVE'), ('EXAM_LEAVE', 'EXAM_LEAVE'), ('MATERNITY_LEAVE', 'MATERNITY_LEAVE'), ('PATERNITY_LEAVE', 'PATERNITY_LEAVE'), ('ANNUAL_LEAVE', 'ANNUAL_LEAVE'), ('COMPASSIONATE_LEAVE', 'COMPASSIONATE_LEAVE')], default='annual', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveClassDetails',
            fields=[
                ('Leave_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Leave_Type', models.CharField(choices=[(0, 'Approved'), (1, 'Pending'), (2, 'Declined'), (3, 'PendingCancellation')], max_length=1)),
                ('Begin_Date', models.DateField(help_text='Leave begin date')),
                ('End_Date', models.DateField(help_text='Leave end date')),
                ('Requested_Days', models.IntegerField(default=0, help_text='Total no of requested leave days')),
                ('Leave_Status', models.IntegerField(choices=[(0, 'Approved'), (1, 'Pending'), (2, 'Declined'), (3, 'PendingCancellation')], default=1)),
                ('Comments', models.CharField(max_length=500, null=True)),
                ('Leave_Attachments', models.FileField(upload_to='leave_management/media/leave_documents')),
                ('Submitted_Date', models.DateTimeField(auto_now_add=True)),
                ('Coverage_Plans', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Created_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-Leave_Id',),
            },
        ),
    ]
