# Generated by Django 3.0.2 on 2020-03-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanergyDepartment',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('approver', models.CharField(blank=True, max_length=300, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('department_code', models.CharField(blank=True, max_length=300, null=True)),
                ('department_status', models.CharField(blank=True, max_length=300, null=True)),
                ('team_lead', models.CharField(blank=True, max_length=1000, null=True)),
                ('team_lead_sf_account', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanergyDepartmentUnit',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('approver', models.CharField(blank=True, max_length=300, null=True)),
                ('department_unit_code', models.CharField(blank=True, max_length=100, null=True)),
                ('line_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('line_manager_sf_account', models.CharField(blank=True, max_length=100, null=True)),
                ('talent_partner_emp_eccount', models.CharField(blank=True, max_length=100, null=True)),
                ('talent_partner', models.CharField(blank=True, max_length=100, null=True)),
                ('team_lead', models.CharField(blank=True, max_length=1000, null=True)),
                ('team_lead_sf_account', models.CharField(blank=True, max_length=1000, null=True)),
                ('uit_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sanergy_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.SanergyDepartment')),
            ],
        ),
    ]
