# Generated by Django 3.0.2 on 2020-02-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Entitlement_Type',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Leave_Type', models.CharField(max_length=50)),
                ('Leave_Group', models.CharField(max_length=50)),
            ],
        ),
    ]
