# Generated by Django 3.0.2 on 2020-03-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200303_1208'),
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Employee'),
        ),
    ]
