# Generated by Django 3.0.2 on 2020-02-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaverequest',
            name='Id',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='employeeleaverequest',
            name='sick_leave_doc_attached',
            field=models.FileField(null=True, upload_to='sick_leave_documents'),
        ),
    ]
