# Generated by Django 3.0.2 on 2020-02-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_leave_entitlement_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave_Entitlement_Type',
        ),
        migrations.RemoveField(
            model_name='leaveclassdetails',
            name='Leave_Owner',
        ),
        migrations.DeleteModel(
            name='LeaveModels',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
        migrations.DeleteModel(
            name='LeaveClassDetails',
        ),
    ]
