# Generated by Django 3.0.2 on 2020-02-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_leave_entitlement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='leave_end_date',
            field=models.DateField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='leave_start_date',
            field=models.DateField(max_length=400, null=True),
        ),
    ]
