# Generated by Django 3.0.2 on 2020-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_auto_20200214_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='startEndDate',
            field=models.DateField(max_length=400, null=True),
        ),
    ]
