# Generated by Django 3.0.2 on 2020-02-17 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_management', '0004_auto_20200214_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanergyCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=100, null=True)),
                ('Decsritption', models.CharField(blank=True, max_length=300, null=True)),
                ('isBusinessDay', models.BooleanField(blank=True, null=True)),
                ('isBusinessDayInclSat', models.BooleanField(blank=True, null=True)),
                ('isHoliday', models.BooleanField(blank=True, null=True)),
                ('isWeekend', models.BooleanField(blank=True, null=True)),
                ('isWeekend_or_Holiday', models.BooleanField(blank=True, null=True)),
                ('Weekday_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Weekday_No', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='no_of_leave_days_requested',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
