# Generated by Django 3.0.2 on 2020-02-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_auto_20200217_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleaverequest',
            name='id',
        ),
        migrations.AddField(
            model_name='employeeleaverequest',
            name='Id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
