# Generated by Django 3.0.2 on 2020-02-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_auto_20200217_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleaverequest',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='stage',
            field=models.DecimalField(decimal_places=3, max_digits=3, max_length=400, null=True),
        ),
    ]
