# Generated by Django 3.0.2 on 2020-03-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200301_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='custom_userid',
            new_name='salesforceid',
        ),
    ]
