# Generated by Django 3.0.2 on 2020-03-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200301_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='salesforceid',
        ),
    ]
