# Generated by Django 3.0.2 on 2020-03-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_salesforceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salesforceid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
