# Generated by Django 3.0.2 on 2020-03-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_salesforceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salesforceid',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
