# Generated by Django 3.0.2 on 2020-03-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200302_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salesforceid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
